project_name: http_eventstore
change:
  version: major
  desc: |
    Make forward readers consistent. Make sure to ReadStreamEventsForward return events in
    correct order: from oldest to newest.

    It's a breaking change for other gems.
