project_name: http_eventstore
change:
  version: minor
  desc: |
    Added temporal fix to HttpEventstore::Helpers::ParseEntries so as an identified [malformed event](http://eventstore.service.consul:2113/web/index.html#/streams/PitchingAggregate-9bc0086b-3a3c-4684-b705-3b064af64cba/3) can be parsed.

